version: "3.8"

services:
  mysql:
    container_name: gestao_vagas_mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DB=gestao_vagas